version: '3.1'

services:
  ghost_blog:
    image: ghost:latest
    container_name: ghost_blog
    restart: always
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__database: ${MYSQL_DATABASE}
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__user: root
      database__connection__port: 3306
      url: https://${GHOST_DOMAIN}
      mail__from: ${GHOST_MAIL_FROM}
      mail__transport: ${GHOST_MAIL_TRANSPORT}
      mail__options__host: ${GHOST_MAIL_OPTIONS_HOST}
      mail__options__port: ${GHOST_MAIL_OPTIONS_PORT}
      mail__options__service: ${GHOST_MAIL_OPTIONS_SERVICE}
      mail__options__auth__user: ${GHOST_MAIL_OPTIONS_AUTH_USER}
      mail__options__auth__pass: ${GHOST_MAIL_OPTIONS_AUTH_PASS}
      mail__options__secure: ${GHOST_MAIL_OPTIONS_SECURE}
    networks:
      - traefik-public
      - mysql-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ghost_blog.tls=true"
      - "traefik.http.routers.ghost_blog.entrypoints=websecure"
      - "traefik.http.routers.ghost_blog.rule=Host(`${GHOST_DOMAIN}`)"
      - "traefik.http.routers.ghost_blog.service=ghost_blog"
      - "traefik.http.services.ghost_blog.loadbalancer.server.port=2368"
      - "traefik.http.routers.ghost_blog.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.ghost_blog-https.redirectscheme.scheme=https"

  mysql:
    image: mysql:8
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks:
      - traefik-public
      - mysql-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN}`)"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.phpmyadmin-https.redirectscheme.scheme=https"

networks:
  traefik-public:
    external: true
  mysql-net:
    external: true